### ISSUE TITLE
Javascript exceptions on widget updates

### ISSUE THREAD

**Issue by dcjones** [shashi/IJuliaWidgets.jl#6]
Maybe I just have the wrong version of something, but I'm getting this now in IJulia.

``` julia
using React, Interact

x = Input(123)

push!(x, 321)
```

```
Exception in Comm callback TypeError {stack: (...), message: "Cannot read property 'selector' of undefined"} TypeError: Cannot read property 'selector' of undefined
    at new OutputArea (http://localhost:8998/static/notebook/js/outputarea.js:22:32)
    at HTMLDivElement.eval (eval at <anonymous> (http://localhost:8998/static/components/jquery/jquery.min.js:4:4231), <anonymous>:25:17)
    at Function.x.extend.each (http://localhost:8998/static/components/jquery/jquery.min.js:4:4575)
    at x.fn.x.each (http://localhost:8998/static/components/jquery/jquery.min.js:4:1626)
    at eval (eval at <anonymous> (http://localhost:8998/static/components/jquery/jquery.min.js:4:4231), <anonymous>:21:36)
    at Comm._maybe_callback (http://localhost:8998/static/services/kernels/js/comm.js:167:17)
    at Comm.handle_msg (http://localhost:8998/static/services/kernels/js/comm.js:175:14)
    at CommManager.comm_msg (http://localhost:8998/static/services/kernels/js/comm.js:106:18)
    at x.isFunction.i (http://localhost:8998/static/components/jquery/jquery.min.js:4:5488)
    at Kernel._handle_iopub_message (http://localhost:8998/static/services/kernels/js/kernel.js:589:13) 
```

And I have to re-eval `x` to see that the value was updated.

**Comment by shashi** [comment]
Okay there have been changes to IPython's OutputArea API, looking into this (I was not on IPython master for quite some time). This stuff is internal to IPython, hence we cannot be sure it won't break again. :|

I can do something similar to ipython/ipython#6066. This comes with the trade-off that the values don't get saved in the notebook, even if you reload the notebook while the kernel is still running.
